if (os_type == os_windows)
    var szDllName = (working_directory + "data\\libraries\\ue.dll")
else if (os_type == os_linux)
    szDllName = (working_directory + "data\\libraries\\libue.so")
else if (os_type == os_linux)
    szDllName = (working_directory + "data\\libraries\\libue.dylib")
global.__def_file_exists_ue = external_define(szDllName, "file_exists_ue", 0, 0, 1, 1)
global.__def_file_delete_ue = external_define(szDllName, "file_delete_ue", 0, 0, 1, 1)
global.__def_file_rename_ue = external_define(szDllName, "file_rename_ue", 0, 0, 2, 1, 1)
global.__def_file_copy_ue = external_define(szDllName, "file_copy_ue", 0, 0, 2, 1, 1)
global.__def_directory_exists_ue = external_define(szDllName, "directory_exists_ue", 0, 0, 1, 1)
global.__def_directory_create_ue = external_define(szDllName, "directory_create_ue", 0, 0, 1, 1)
global.__def_directory_delete_ue = external_define(szDllName, "directory_delete_ue", 0, 0, 1, 1)
global.__def_directory_rename_ue = external_define(szDllName, "directory_rename_ue", 0, 0, 2, 1, 1)
global.__def_file_text_open_write_ue = external_define(szDllName, "file_text_open_write_ue", 0, 1, 1, 1)
global.__def_file_text_open_read_ue = external_define(szDllName, "file_text_open_read_ue", 0, 1, 1, 1)
global.__def_file_text_open_append_ue = external_define(szDllName, "file_text_open_append_ue", 0, 1, 1, 1)
global.__def_file_text_readln_ue = external_define(szDllName, "file_text_readln_ue", 0, 1, 1, 1)
global.__def_file_text_writeln_ue = external_define(szDllName, "file_text_writeln_ue", 0, 0, 2, 1, 1)
global.__def_file_text_eof_ue = external_define(szDllName, "file_text_eof_ue", 0, 0, 1, 1)
global.__def_file_text_close_ue = external_define(szDllName, "file_text_close_ue", 0, 0, 1, 1)
global.__def_file_find_first_ue = external_define(szDllName, "file_find_first_ue", 0, 1, 1, 1)
global.__def_file_find_next_ue = external_define(szDllName, "file_find_next_ue", 0, 1, 0)
global.__def_file_find_attributes_ue = external_define(szDllName, "file_find_attributes_ue", 0, 0, 0)
global.__def_file_find_size_ue = external_define(szDllName, "file_find_size_ue", 0, 0, 0)
global.__def_file_find_close_ue = external_define(szDllName, "file_find_close_ue", 0, 0, 0)
global.__def_working_directory_ue = external_define(szDllName, "working_directory_ue", 0, 1, 0)
global.__def_environment_get_variable_ue = external_define(szDllName, "environment_get_variable_ue", 0, 1, 1, 1)
