if (instance_number(obj_leafs) > 1 || instance_exists(obj_rain) || instance_exists(obj_snow) || instance_exists(obj_ash))
    instance_destroy()
leafs_preset_direction = 2
leafs = part_system_create()
part_system_depth(leafs, 1000)
leafsflake = part_type_create()
part_type_alpha2(leafsflake, 1, 0)
part_type_speed(leafsflake, 3, 8, 0, 0)
part_type_life(leafsflake, 300, 400)
part_type_sprite(leafsflake, 1854, 0, 0, 0)
part_type_size(leafsflake, 0.5, 1, 0, 0)
part_type_orientation(leafsflake, 0, 360, 0, 0, 0)
leafs_emitter = part_emitter_create(leafs)
part_emitter_region(leafs, leafs_emitter, view_xview[0], (view_xview[0] + room_width), -10, -5, 1, 0)
part_emitter_stream(leafs, leafs_emitter, leafsflake, 3)
repeat (100)
    part_system_update(leafs)
