if (instance_number(obj_ash) > 1 || instance_exists(obj_rain) || instance_exists(obj_snow) || instance_exists(obj_leafs))
    instance_destroy()
ash_preset_direction = 2
ash = part_system_create()
part_system_depth(ash, 1000)
ashflake = part_type_create()
part_type_alpha2(ashflake, 1, 0)
part_type_color_mix(ashflake, 12632256, 8421504)
part_type_speed(ashflake, 1, 6, 0, 0)
part_type_life(ashflake, 300, 400)
part_type_shape(ashflake, 12)
part_type_size(ashflake, 0.05, 0.1, 0, 0)
ash_emitter = part_emitter_create(ash)
part_emitter_region(ash, ash_emitter, view_xview[0], (view_xview[0] + room_width), -10, -5, 1, 0)
part_emitter_stream(ash, ash_emitter, ashflake, 3)
repeat (100)
    part_system_update(ash)
