if (instance_number(obj_snow) > 1 || instance_exists(obj_rain) || instance_exists(obj_ash) || instance_exists(obj_leafs))
    instance_destroy()
snow_preset_direction = 2
snow = part_system_create()
part_system_depth(snow, 1000)
snowflake = part_type_create()
part_type_alpha2(snowflake, 1, 0)
part_type_color_mix(snowflake, 16777215, 12632256)
part_type_speed(snowflake, 1, 2, 0, 0)
part_type_life(snowflake, 300, 400)
part_type_shape(snowflake, 13)
part_type_size(snowflake, 0.05, 0.1, 0, 0)
snow_emitter = part_emitter_create(snow)
part_emitter_region(snow, snow_emitter, view_xview[0], (view_xview[0] + room_width), -10, -5, 0, 0)
part_emitter_stream(snow, snow_emitter, snowflake, 3)
repeat (100)
    part_system_update(snow)
